[package]
name = "binary-heap-plus2"
version = "0.3.2"
authors = ["SEKINE, Hideki <sekineh@me.com>"]
description = "Enhanced version of std::collections::BinaryHeap that supports max, min, and custom-order heaps."
license = "MIT"
repository = "https://github.com/davidli2010/binary-heap-plus-rs"
documentation = "https://docs.rs/binary-heap-plus2/"
readme = "README.md"
keywords = ["binary", "heap", "priority", "queue"]
categories = ["data-structures", "algorithms", ]
edition = "2018"

[dependencies]
compare = "0.1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.56"

[badges]
# TODO: waiting for PR to land...: https://github.com/rust-lang/crates.io/pull/1838#
# github-actions = { repository = "sekineh/binary-heap-plus-rs", workflow = "Rust" }